name: "build-n-test"
resources:
  containers:
    - container: u-dev-18-04
      image: quay.io/airmap/dev:18.04
trigger:
  branches:
    include:
      - "airmap/1.3.4-adapter"
jobs:
  - job: "pr"
    strategy:
      parallel: 1
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - checkout: self
        clean: true
        lfs: true
        submodules: recursive
        persistCredentials: true
      - bash: |
          set -exo pipefail
          if [[ "${BUILD_SOURCEBRANCHNAME}" != "1.3.4-adapter" ]]; then
            export GOPATH=/tmp/go
            export PATH=${GOPATH}/bin:${PATH}
            mkdir -p ${GOPATH}/src/istio.io/istio
            cp -R . ${GOPATH}/src/istio.io/istio
            cd ${GOPATH}/src/istio.io/istio
            make build
          fi
        name: "build_pr"
        displayName: "Build PR"
  - job: "image"
    strategy:
      parallel: 1
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - checkout: self
        clean: true
        lfs: true
        submodules: recursive
        persistCredentials: true
      - bash: |
          set -exo pipefail
          if [[ "${BUILD_SOURCEBRANCHNAME}" == "1.3.4-adapter" ]]; then
            docker login $REGISTRY -u $ACR_USERNAME -p $ACR_PASSWORD
            export GOPATH=/tmp/go
            export PATH=${GOPATH}/bin:${PATH}
            mkdir -p ${GOPATH}/src/istio.io/istio
            cp -R . ${GOPATH}/src/istio.io/istio
            cd ${GOPATH}/src/istio.io/istio
            make build
            make push.docker.mixer HUB=${REGISTRY}/istio TAG=$(git rev-parse --short HEAD)
            make push.docker.pilot HUB=${REGISTRY}/istio TAG=$(git rev-parse --short HEAD)
            make push.docker.galley HUB=${REGISTRY}/istio TAG=$(git rev-parse --short HEAD)
          fi
        name: "build_image"
        displayName: "Build image"
        env:
          ACR_USERNAME: $(acr.Username)
          ACR_PASSWORD: $(acr.Password)
          REGISTRY: $(acr.Registry)
